on:
  push:
    branches:
      - master

jobs:
  builddeploy:
    runs-on: ubuntu-latest
    name: Build ikiwiki and deploy
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Build Docker image.
        run: |
            docker build -t geekout .
      - name: Generate ikiwiki site
        run: |
            docker run -v $PWD/out:/home/jamie/geekout.org.uk/out geekout
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: S3 Sync to deploy
        run: |
          aws s3 sync --acl public-read out/ s3://geekout.org.uk --delete
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E370I3E7LZAIF1 \
            --paths '/*'
